export const products = [
  {
    id: 1,
    name: "HALO LOUNGE CHAIR",
    category: "Handmade",
    price: "$149.00",
    stock: 11,
  },
  {
    id: 2,
    name: "CEILING LAMPS",
    category: "Luxury",
    price: "$59.00",
    stock: 12,
  },
  {
    id: 3,
    name: "DECORATIVE MIRROR",
    category: "Handmade",
    price: "$69.00",
    stock: 12,
  },
  {
    id: 4,
    name: "BEDSIDE TAB",
    category: "Wooden",
    price: "$99.00",
    stock: 12,
  },
  {
    id: 5,
    name: "DINING TABLE",
    category: "Handmade",
    price: "$949.00",
    stock: 12,
  },
  {
    id: 6,
    name: "CLASSIC TABLE LAMP",
    category: "Handmade",
    price: "$49.00",
    stock: 12,
  },
  {
    id: 7,
    name: "LEATHER BED",
    category: "Luxury",
    price: "$999.00",
    stock: 12,
  },
  {
    id: 8,
    name: "LEATHER BED",
    category: "Luxury",
    price: "$999.00",
    stock: 12,
  },
  {
    id: 9,
    name: "WORKING TABLE",
    category: "Luxury",
    price: "$1199.00",
  },
  {
    id: 10,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 11,
    name: "DRESSING TABLE",
    category: "Wooden",
    price: "$219.00",
  },
  {
    id: 12,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 13,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 14,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 15,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 16,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 17,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 18,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 19,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 20,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 21,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 22,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 23,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 24,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 25,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 26,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 27,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 28,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 29,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 30,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 31,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 32,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 33,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 34,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 35,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 36,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 37,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 38,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 39,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 40,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 41,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
  {
    id: 42,
    name: "SHOES CABINET",
    category: "Wooden",
    price: "$1399.00",
  },
];
